<?php

namespace RecordStoreBundle\Repository;

/**
 * CartOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchUsersOrdersByStatus($status, $user)
    {
        $qb  = $this->createQueryBuilder('o');
        $qb->select('o')
            ->join('o.user', 'u')
            ->join('o.product', 'p')
            ->where($qb->expr()->eq('o.status', ':status'))
            ->andWhere($qb->expr()->eq('o.user', ':user'))
            ->setParameters([
                'status' => $status,
                'user' => $user
            ]);

        return $qb->getQuery()->getResult();
    }

}
