<?php

namespace RecordStoreBundle\Repository;

/**
 * CartOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
